CREATE DATABASE ECOM_INGESTION_DB;

CREATE SCHEMA ECOM_INGESTION_DB.RAW;
CREATE SCHEMA ECOM_INGESTION_DB.STAGING;
CREATE SCHEMA ECOM_INGESTION_DB.CLEAN;
CREATE SCHEMA ECOM_INGESTION_DB.FINAL;

CREATE STAGE ECOM_INGESTION_DB.RAW.RAW_STAGE;

LIST @ECOM_INGESTION_DB.RAW.RAW_STAGE;


CREATE OR REPLACE FILE FORMAT ECOM_INGESTION_DB.RAW.RAW_CSV_FORMAT

  TYPE = 'CSV',
  FIELD_DELIMITER = ',',
  PARSE_HEADER = TRUE,
  FIELD_OPTIONALLY_ENCLOSED_BY = '"',
  NULL_IF = ('NULL', 'null', '', 'NaN'),
  EMPTY_FIELD_AS_NULL = TRUE,
  TRIM_SPACE = TRUE
  ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
;


-- Creating BRONZE TABLES
CREATE OR REPLACE TABLE ECOM_INGESTION_DB.RAW.CUSTOMERS_BRONZE (
    CUSTOMER_ID INT,
    NAME STRING,
    EMAIL STRING,
    SIGNUP_DATE STRING,
    IS_ACTIVE STRING,
    UPLOAD_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);
--Since you are using MATCH_BY_COLUMN_NAME, ensure you have run this command at least once to allow the table to accept the columns from your files:
ALTER TABLE ECOM_INGESTION_DB.RAW.CUSTOMERS_BRONZE SET ENABLE_SCHEMA_EVOLUTION = TRUE;

list @ECOM_INGESTION_DB.RAW.RAW_STAGE/customers;

COPY INTO ECOM_INGESTION_DB.RAW.CUSTOMERS_BRONZE
FROM @ECOM_INGESTION_DB.RAW.RAW_STAGE
PATTERN = '.*customers_part.*\.csv\.gz'
FILE_FORMAT = (FORMAT_NAME = 'ECOM_INGESTION_DB.RAW.RAW_CSV_FORMAT')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

SHOW FILE FORMATS IN SCHEMA ECOM_INGESTION_DB.RAW;

SELECT * FROM ECOM_INGESTION_DB.RAW.CUSTOMERS_BRONZE
